### ISSUE TITLE
Can I use it with NSData instead URL?

### ISSUE THREAD

**Issue by Cleversou1983** [fulldecent/FDWaveformView#138]
I have a audio saved on a Realm Database as NSData. With AVAudioPlayer I can success load the data and play the audio. I'm willing to use FDWaveformView to display the sound waves, but I couldn't found a way to make it work with NSData instead URL...

**Comment by fulldecent** [comment]
We are relying on this feature to load audio: 

https://developer.apple.com/documentation/avfoundation/avurlasset/1385698-init

I agree that the framework could include an alternate initializer to load from NSData instead of a URL. But that is a matter for you to take up with Apple.

Also this is URL, not URI, so you can't just make a data URI.

Unfortunately it appears you will need to either save the file or come up with a clever streaming approach.

**Comment by foolbear** [comment]
I have the same requirement. audio data is produced from an audio file from the other peer. 
data = (try? Data(contentsOf: URL(fileURLWithPath: path))) ?? Data(). 

I don't want to save data to file again. Maybe AVAssetResourceLoader will work, but I'm not success yet.

**Comment by fulldecent** [comment]
Thank you for the discussion. I'm closing this now as a question. But if somebody would like to refactor some of this I will be happy to review a PR.

**Comment by fulldecent** [comment]
Actually #139 is the continuation of this

**Comment by matvelius** [comment]
Hey, could you help me unsubscribe from this thread? Can't seem to figure
out how to do it :)

Matvey Kostukovsky  | *Director of Music Education, co-founder*

* TERRA**SOUNDS **School of Music & Arts*
924 Waukegan Rd. *|* Glenview, IL 60025 *|* *847.737.1850 x 111* *|*
*terrasounds.com
<http://terrasounds.com/>*

**Comment by fulldecent** [comment]
@matvelius I can't do it for you. But you can click here.

<img width="1552" alt="Screen Shot 2020-08-25 at 16 33 09" src="https://user-images.githubusercontent.com/382183/91224874-bb788a00-e6f0-11ea-9589-c7fd78afe6c2.png">

And if you are reading this on an email alert, there is an UNSUBSCRIBE at bottom.
