### ISSUE TITLE
iOS Example: FDWaveformView failed to load AVAssetTrack for ogg file

### ISSUE THREAD

**Issue by Dario-Gasquez** [fulldecent/FDWaveformView#147]
Hi,

I tried the sample iOS app, it works with the .mp3 and .aac sample files, but when I try connecting and loading the ogg file it gives me the following error:
```FDWaveformView failed to load AVAssetTrack```

An additional screenshot showing the change made to load the ogg file and the place where the error occurs:
![LoadOGG-error](https://user-images.githubusercontent.com/19808804/130642679-07b0f1c5-bd41-4e51-95a6-e34b864fd872.png)

Is ogg currently not supported?

Thanks in advance.

**Comment by fulldecent** [comment]
I think the problem is that certain Apple devices / operating system versions support OGG and some don't. And of course this is different with simulator and real device.

---

I forget which is supported or not. And this is probably not a bug with the functionality of FDWaveformView. But we should find this authoritative link that describes which codecs Apple supports on which devices/OS/simulators and include that in documentation.

**Comment by Dario-Gasquez** [comment]
Thanks for the quick answer. 
Should I find said authoritative source if information I'll comment about it here (or even a PR to the README?)

**Comment by fulldecent** [comment]
Yes, CAF is definitely supported.

That is a good link. If there is something directly published by Apple that would be preferred.

**Comment by fulldecent** [comment]
The example app is updated now. https://github.com/fulldecent/FDWaveformView/blob/f470d434969778ede228b8041c6679bc8ae4f4e3/Example/Sources/ContentView.swift

I still see that simulator does not support  OGG but real devices do.
