### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#9]
Allowing zooming, or displaying only part of the song.

Some notes on seeking an `AVAssetReader` are at http://stackoverflow.com/questions/13210684/reading-samples-with-avassetreader-and-timerange-in-real-time

**Comment by fulldecent** [comment]
Hi @pixlwave Just wanted to follow up, does this project still wore with RubyMotion? And is there anything we should add to our test suite to support this target?

**Comment by pixlwave** [comment]
So I no longer use RubyMotion, but I believe that since the move to Swift this project no longer works with it for 2 reasons:

- RubyMotion needs Objective-C headers in order to generate the bridge to the Objective-C runtime. This one would be fixable by enabling Xcode to auto-generate the headers, however;
- I don't believe that RubyMotion is aware to copy in the necessary swift runtime libraries in this situation so the user needs to do so manually (I was experimenting with this just before I made the switch and can't remember the specifics of how well it worked).

All this said, I believe that Swift compatibility is one of the aims of RubyMotion to move forwards, and to answer your second question, if they implement this in the same way as their Objective-C bridge, it would be very unlikely that any additional tests would be required as it's a pretty much transparent process.

**Comment by fulldecent** [comment]
Thank you for explaining. Excellent. So it appears that we do not need to worry about them being downstream.
